USE ROLE ACCOUNTADMIN;
USE DATABASE RECOMART_DB;

SELECT
    'RAW_EVENTS' AS CHECK_NAME,
    COUNT(*) AS RECORD_COUNT
FROM RAW.RAW_RECOMART_EVENTS

UNION ALL

SELECT
    'VALIDATED_EVENTS' AS CHECK_NAME,
    COUNT(*) AS RECORD_COUNT
FROM VALIDATED.RECOMART_EVENTS

UNION ALL

SELECT
    'CURATED_USER_ITEM_INTERACTIONS' AS CHECK_NAME,
    COUNT(*) AS RECORD_COUNT
FROM CURATED.USER_ITEM_INTERACTIONS

UNION ALL

SELECT
    'OFFLINE_FEATURES' AS CHECK_NAME,
    COUNT(*) AS RECORD_COUNT
FROM FEATURE_STORE.OFFLINE_RECOMMENDATION_FEATURES

UNION ALL

SELECT
    'MODEL_RUNS' AS CHECK_NAME,
    COUNT(*) AS RECORD_COUNT
FROM ML_MONITORING.MODEL_RUNS;