USE ROLE ACCOUNTADMIN;
USE DATABASE RECOMART_DB;

CREATE SCHEMA IF NOT EXISTS ML_MONITORING;

CREATE TABLE IF NOT EXISTS ML_MONITORING.MODEL_RUNS (
    RUN_ID              VARCHAR,
    MODEL_NAME          VARCHAR,
    MODEL_VERSION       VARCHAR,
    MODEL_TYPE          VARCHAR,

    TRAINING_START_TS   TIMESTAMP_NTZ,
    TRAINING_END_TS     TIMESTAMP_NTZ,
    TRAINING_STATUS     VARCHAR,

    TRAINING_DATASET    VARCHAR,
    FEATURE_VERSION     VARCHAR,
    SOURCE_VALIDATION_BATCH_ID VARCHAR,

    PARAMETERS          VARIANT,
    METRICS             VARIANT,
    MODEL_ARTIFACT_PATH VARCHAR,
    MLFLOW_RUN_ID       VARCHAR,

    CREATED_BY          VARCHAR DEFAULT CURRENT_USER(),
    CREATED_TS          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS ML_MONITORING.MODEL_METRICS (
    RUN_ID              VARCHAR,
    MODEL_NAME          VARCHAR,
    MODEL_VERSION       VARCHAR,

    METRIC_NAME         VARCHAR,
    METRIC_VALUE        FLOAT,
    K_VALUE             NUMBER(38,0),

    FEATURE_VERSION     VARCHAR,
    SOURCE_VALIDATION_BATCH_ID VARCHAR,
    EVALUATION_DATE     DATE,
    CREATED_TS          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS ML_MONITORING.RECOMMENDATION_RESULTS (
    REQUEST_ID              VARCHAR,
    USER_ID                 NUMBER(38,0),
    ITEM_ID                 NUMBER(38,0),

    RANK_POSITION           NUMBER(38,0),
    RECOMMENDATION_SCORE    FLOAT,

    MODEL_NAME              VARCHAR,
    MODEL_VERSION           VARCHAR,
    FEATURE_VERSION         VARCHAR,
    SOURCE_VALIDATION_BATCH_ID VARCHAR,

    GENERATED_TS            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);