USE ROLE ACCOUNTADMIN;
USE DATABASE RECOMART_DB;

-- Latest model runs
SELECT
    RUN_ID,
    MODEL_NAME,
    MODEL_VERSION,
    MODEL_TYPE,
    TRAINING_STATUS,
    FEATURE_VERSION,
    SOURCE_VALIDATION_BATCH_ID,
    MODEL_ARTIFACT_PATH,
    MLFLOW_RUN_ID,
    TRAINING_START_TS,
    TRAINING_END_TS,
    CREATED_TS
FROM ML_MONITORING.MODEL_RUNS
ORDER BY CREATED_TS DESC;

-- Latest model metrics
SELECT
    RUN_ID,
    MODEL_NAME,
    MODEL_VERSION,
    METRIC_NAME,
    METRIC_VALUE,
    K_VALUE,
    FEATURE_VERSION,
    SOURCE_VALIDATION_BATCH_ID,
    EVALUATION_DATE,
    CREATED_TS
FROM ML_MONITORING.MODEL_METRICS
ORDER BY CREATED_TS DESC, METRIC_NAME;

-- Sample recommendation results
SELECT
    REQUEST_ID,
    USER_ID,
    ITEM_ID,
    RANK_POSITION,
    RECOMMENDATION_SCORE,
    MODEL_NAME,
    MODEL_VERSION,
    FEATURE_VERSION,
    SOURCE_VALIDATION_BATCH_ID,
    GENERATED_TS
FROM ML_MONITORING.RECOMMENDATION_RESULTS
ORDER BY GENERATED_TS DESC, USER_ID, RANK_POSITION
LIMIT 100;