SELECT COUNT(*) AS MODEL_RUN_COUNT
FROM ML_MONITORING.MODEL_RUNS;


SELECT
    METRIC_NAME,
    METRIC_VALUE,
    K_VALUE
FROM ML_MONITORING.MODEL_METRICS
WHERE RUN_ID = (
    SELECT RUN_ID
    FROM ML_MONITORING.MODEL_RUNS
    ORDER BY CREATED_TS DESC
    LIMIT 1
)
ORDER BY METRIC_NAME;


SELECT
    USER_ID,
    ITEM_ID,
    RANK_POSITION,
    RECOMMENDATION_SCORE
FROM ML_MONITORING.RECOMMENDATION_RESULTS
ORDER BY GENERATED_TS DESC, USER_ID, RANK_POSITION
LIMIT 20;