USE ROLE ACCOUNTADMIN;
USE DATABASE RECOMART_DB;

CREATE TABLE IF NOT EXISTS CURATED.CLEAN_RECOMART_EVENTS (
    EVENT_ID                    VARCHAR,
    EVENT_TIMESTAMP_MS          NUMBER(38,0),
    EVENT_TS                    TIMESTAMP_NTZ,
    EVENT_DATE                  DATE,
    EVENT_HOUR                  NUMBER(2,0),
    EVENT_DAY_OF_WEEK           NUMBER(1,0),

    USER_ID                     NUMBER(38,0),
    ITEM_ID                     NUMBER(38,0),
    EVENT_TYPE                  VARCHAR,
    EVENT_TYPE_ENCODED          NUMBER(1,0),
    EVENT_WEIGHT                FLOAT,
    TRANSACTION_ID              NUMBER(38,0),

    SOURCE_FILE_NAME            VARCHAR,
    INGESTION_DATE              DATE,
    LOAD_TS                     TIMESTAMP_NTZ,

    SOURCE_VALIDATION_BATCH_ID  VARCHAR,
    PREPARATION_RUN_TS          TIMESTAMP_NTZ,
    CREATED_TS                  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CURATED.CLEAN_RECOMART_ITEM_PROPERTIES (
    ITEM_PROPERTY_ID            VARCHAR,
    PROPERTY_TS                 TIMESTAMP_NTZ,
    ITEM_ID                     NUMBER(38,0),
    PROPERTY_NAME               VARCHAR,
    PROPERTY_VALUE              VARCHAR,
    PROPERTY_VALUE_NUMERIC      FLOAT,

    SOURCE_FILE_NAME            VARCHAR,
    INGESTION_DATE              DATE,
    LOAD_TS                     TIMESTAMP_NTZ,

    SOURCE_VALIDATION_BATCH_ID  VARCHAR,
    PREPARATION_RUN_TS          TIMESTAMP_NTZ,
    CREATED_TS                  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CURATED.CLEAN_RECOMART_CATEGORY_TREE (
    CATEGORY_ID                 NUMBER(38,0),
    PARENT_CATEGORY_ID          NUMBER(38,0),
    IS_ROOT_CATEGORY            BOOLEAN,

    SOURCE_FILE_NAME            VARCHAR,
    INGESTION_DATE              DATE,
    LOAD_TS                     TIMESTAMP_NTZ,

    SOURCE_VALIDATION_BATCH_ID  VARCHAR,
    PREPARATION_RUN_TS          TIMESTAMP_NTZ,
    CREATED_TS                  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CURATED.CLEAN_EXTERNAL_PRODUCTS (
    PRODUCT_ID                  NUMBER(38,0),
    PRODUCT_TITLE               VARCHAR,
    PRODUCT_DESCRIPTION         VARCHAR,
    CATEGORY                    VARCHAR,
    PRICE                       FLOAT,
    NORMALIZED_PRICE            FLOAT,
    RATING                      FLOAT,
    NORMALIZED_RATING           FLOAT,
    STOCK                       NUMBER(38,0),
    BRAND                       VARCHAR,

    SOURCE_VALIDATION_BATCH_ID  VARCHAR,
    PREPARATION_RUN_TS          TIMESTAMP_NTZ,
    CREATED_TS                  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

ALTER TABLE CURATED.USER_ITEM_INTERACTIONS
ADD COLUMN IF NOT EXISTS SOURCE_VALIDATION_BATCH_ID VARCHAR;

ALTER TABLE CURATED.USER_ITEM_INTERACTIONS
ADD COLUMN IF NOT EXISTS PREPARATION_RUN_TS TIMESTAMP_NTZ;

ALTER TABLE CURATED.USER_FEATURES
ADD COLUMN IF NOT EXISTS SOURCE_VALIDATION_BATCH_ID VARCHAR;

ALTER TABLE CURATED.USER_FEATURES
ADD COLUMN IF NOT EXISTS PREPARATION_RUN_TS TIMESTAMP_NTZ;

ALTER TABLE CURATED.USER_FEATURES
ADD COLUMN IF NOT EXISTS NORMALIZED_TOTAL_VIEWS FLOAT;

ALTER TABLE CURATED.USER_FEATURES
ADD COLUMN IF NOT EXISTS NORMALIZED_TOTAL_TRANSACTIONS FLOAT;

ALTER TABLE CURATED.ITEM_FEATURES
ADD COLUMN IF NOT EXISTS SOURCE_VALIDATION_BATCH_ID VARCHAR;

ALTER TABLE CURATED.ITEM_FEATURES
ADD COLUMN IF NOT EXISTS PREPARATION_RUN_TS TIMESTAMP_NTZ;

ALTER TABLE CURATED.ITEM_FEATURES
ADD COLUMN IF NOT EXISTS NORMALIZED_POPULARITY_SCORE FLOAT;