USE ROLE ACCOUNTADMIN;
USE DATABASE RECOMART_DB;

SET SOURCE_VALIDATION_BATCH_ID = (
    SELECT SOURCE_VALIDATION_BATCH_ID
    FROM CURATED.CLEAN_RECOMART_EVENTS
    WHERE SOURCE_VALIDATION_BATCH_ID IS NOT NULL
    ORDER BY PREPARATION_RUN_TS DESC
    LIMIT 1
);

SET PREPARATION_RUN_TS = CURRENT_TIMESTAMP();

DELETE FROM CURATED.USER_ITEM_INTERACTIONS
WHERE SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID;

INSERT INTO CURATED.USER_ITEM_INTERACTIONS (
    USER_ID,
    ITEM_ID,
    VIEW_COUNT,
    ADD_TO_CART_COUNT,
    TRANSACTION_COUNT,
    FIRST_INTERACTION_TS,
    LAST_INTERACTION_TS,
    IMPLICIT_SCORE,
    INGESTION_DATE,
    SOURCE_VALIDATION_BATCH_ID,
    PREPARATION_RUN_TS,
    CREATED_TS,
    UPDATED_TS
)
SELECT
    USER_ID,
    ITEM_ID,

    COUNT_IF(EVENT_TYPE = 'view') AS VIEW_COUNT,
    COUNT_IF(EVENT_TYPE = 'addtocart') AS ADD_TO_CART_COUNT,
    COUNT_IF(EVENT_TYPE = 'transaction') AS TRANSACTION_COUNT,

    MIN(EVENT_TS) AS FIRST_INTERACTION_TS,
    MAX(EVENT_TS) AS LAST_INTERACTION_TS,

    SUM(EVENT_WEIGHT) AS IMPLICIT_SCORE,
    MAX(INGESTION_DATE) AS INGESTION_DATE,

    $SOURCE_VALIDATION_BATCH_ID AS SOURCE_VALIDATION_BATCH_ID,
    $PREPARATION_RUN_TS AS PREPARATION_RUN_TS,
    CURRENT_TIMESTAMP() AS CREATED_TS,
    CURRENT_TIMESTAMP() AS UPDATED_TS
FROM CURATED.CLEAN_RECOMART_EVENTS
WHERE SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID
GROUP BY USER_ID, ITEM_ID;