USE ROLE ACCOUNTADMIN;
USE DATABASE RECOMART_DB;

SET SOURCE_VALIDATION_BATCH_ID = (
    SELECT SOURCE_VALIDATION_BATCH_ID
    FROM CURATED.CLEAN_RECOMART_EVENTS
    WHERE SOURCE_VALIDATION_BATCH_ID IS NOT NULL
    ORDER BY PREPARATION_RUN_TS DESC
    LIMIT 1
);

SET PREPARATION_RUN_TS = CURRENT_TIMESTAMP();

DELETE FROM CURATED.USER_FEATURES
WHERE SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID;

DELETE FROM CURATED.ITEM_FEATURES
WHERE SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID;

DELETE FROM CURATED.PRODUCT_CATALOG_FEATURES;


-- ============================================================
-- 1. User features
-- ============================================================

INSERT INTO CURATED.USER_FEATURES (
    USER_ID,
    TOTAL_VIEWS,
    TOTAL_ADD_TO_CARTS,
    TOTAL_TRANSACTIONS,
    UNIQUE_ITEMS_VIEWED,
    UNIQUE_ITEMS_PURCHASED,
    AVG_INTERACTION_SCORE,
    USER_ACTIVITY_LEVEL,
    FIRST_SEEN_TS,
    LAST_SEEN_TS,
    FEATURE_VERSION,
    SOURCE_VALIDATION_BATCH_ID,
    PREPARATION_RUN_TS,
    NORMALIZED_TOTAL_VIEWS,
    NORMALIZED_TOTAL_TRANSACTIONS,
    CREATED_TS,
    UPDATED_TS
)
WITH user_base AS (
    SELECT
        USER_ID,
        SUM(VIEW_COUNT) AS TOTAL_VIEWS,
        SUM(ADD_TO_CART_COUNT) AS TOTAL_ADD_TO_CARTS,
        SUM(TRANSACTION_COUNT) AS TOTAL_TRANSACTIONS,
        COUNT(DISTINCT CASE WHEN VIEW_COUNT > 0 THEN ITEM_ID END) AS UNIQUE_ITEMS_VIEWED,
        COUNT(DISTINCT CASE WHEN TRANSACTION_COUNT > 0 THEN ITEM_ID END) AS UNIQUE_ITEMS_PURCHASED,
        AVG(IMPLICIT_SCORE) AS AVG_INTERACTION_SCORE,
        MIN(FIRST_INTERACTION_TS) AS FIRST_SEEN_TS,
        MAX(LAST_INTERACTION_TS) AS LAST_SEEN_TS
    FROM CURATED.USER_ITEM_INTERACTIONS
    WHERE SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID
    GROUP BY USER_ID
),
stats AS (
    SELECT
        MIN(TOTAL_VIEWS) AS MIN_TOTAL_VIEWS,
        MAX(TOTAL_VIEWS) AS MAX_TOTAL_VIEWS,
        MIN(TOTAL_TRANSACTIONS) AS MIN_TOTAL_TRANSACTIONS,
        MAX(TOTAL_TRANSACTIONS) AS MAX_TOTAL_TRANSACTIONS
    FROM user_base
)
SELECT
    u.USER_ID,
    u.TOTAL_VIEWS,
    u.TOTAL_ADD_TO_CARTS,
    u.TOTAL_TRANSACTIONS,
    u.UNIQUE_ITEMS_VIEWED,
    u.UNIQUE_ITEMS_PURCHASED,
    u.AVG_INTERACTION_SCORE,

    CASE
        WHEN u.TOTAL_TRANSACTIONS >= 5 OR u.TOTAL_VIEWS >= 50 THEN 'HIGH'
        WHEN u.TOTAL_TRANSACTIONS >= 1 OR u.TOTAL_VIEWS >= 10 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS USER_ACTIVITY_LEVEL,

    u.FIRST_SEEN_TS,
    u.LAST_SEEN_TS,
    'v1' AS FEATURE_VERSION,
    $SOURCE_VALIDATION_BATCH_ID AS SOURCE_VALIDATION_BATCH_ID,
    $PREPARATION_RUN_TS AS PREPARATION_RUN_TS,

    CASE
        WHEN s.MAX_TOTAL_VIEWS = s.MIN_TOTAL_VIEWS THEN 0
        ELSE (u.TOTAL_VIEWS - s.MIN_TOTAL_VIEWS) / NULLIF((s.MAX_TOTAL_VIEWS - s.MIN_TOTAL_VIEWS), 0)
    END AS NORMALIZED_TOTAL_VIEWS,

    CASE
        WHEN s.MAX_TOTAL_TRANSACTIONS = s.MIN_TOTAL_TRANSACTIONS THEN 0
        ELSE (u.TOTAL_TRANSACTIONS - s.MIN_TOTAL_TRANSACTIONS) / NULLIF((s.MAX_TOTAL_TRANSACTIONS - s.MIN_TOTAL_TRANSACTIONS), 0)
    END AS NORMALIZED_TOTAL_TRANSACTIONS,

    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
FROM user_base u
CROSS JOIN stats s;


-- ============================================================
-- 2. Item features
-- ============================================================

INSERT INTO CURATED.ITEM_FEATURES (
    ITEM_ID,
    TOTAL_VIEWS,
    TOTAL_ADD_TO_CARTS,
    TOTAL_TRANSACTIONS,
    UNIQUE_USERS,
    ITEM_POPULARITY_SCORE,
    CONVERSION_RATE,
    ITEM_ACTIVITY_LEVEL,
    FIRST_INTERACTION_TS,
    LAST_INTERACTION_TS,
    FEATURE_VERSION,
    SOURCE_VALIDATION_BATCH_ID,
    PREPARATION_RUN_TS,
    NORMALIZED_POPULARITY_SCORE,
    CREATED_TS,
    UPDATED_TS
)
WITH item_base AS (
    SELECT
        ITEM_ID,
        SUM(VIEW_COUNT) AS TOTAL_VIEWS,
        SUM(ADD_TO_CART_COUNT) AS TOTAL_ADD_TO_CARTS,
        SUM(TRANSACTION_COUNT) AS TOTAL_TRANSACTIONS,
        COUNT(DISTINCT USER_ID) AS UNIQUE_USERS,
        MIN(FIRST_INTERACTION_TS) AS FIRST_INTERACTION_TS,
        MAX(LAST_INTERACTION_TS) AS LAST_INTERACTION_TS,

        SUM(VIEW_COUNT * 1 + ADD_TO_CART_COUNT * 3 + TRANSACTION_COUNT * 5) AS ITEM_POPULARITY_SCORE,

        CASE
            WHEN SUM(VIEW_COUNT) = 0 THEN 0
            ELSE SUM(TRANSACTION_COUNT) / NULLIF(SUM(VIEW_COUNT), 0)
        END AS CONVERSION_RATE
    FROM CURATED.USER_ITEM_INTERACTIONS
    WHERE SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID
    GROUP BY ITEM_ID
),
stats AS (
    SELECT
        MIN(ITEM_POPULARITY_SCORE) AS MIN_POPULARITY,
        MAX(ITEM_POPULARITY_SCORE) AS MAX_POPULARITY
    FROM item_base
)
SELECT
    i.ITEM_ID,
    i.TOTAL_VIEWS,
    i.TOTAL_ADD_TO_CARTS,
    i.TOTAL_TRANSACTIONS,
    i.UNIQUE_USERS,
    i.ITEM_POPULARITY_SCORE,
    i.CONVERSION_RATE,

    CASE
        WHEN i.ITEM_POPULARITY_SCORE >= 100 THEN 'HIGH'
        WHEN i.ITEM_POPULARITY_SCORE >= 20 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS ITEM_ACTIVITY_LEVEL,

    i.FIRST_INTERACTION_TS,
    i.LAST_INTERACTION_TS,
    'v1' AS FEATURE_VERSION,
    $SOURCE_VALIDATION_BATCH_ID AS SOURCE_VALIDATION_BATCH_ID,
    $PREPARATION_RUN_TS AS PREPARATION_RUN_TS,

    CASE
        WHEN s.MAX_POPULARITY = s.MIN_POPULARITY THEN 0
        ELSE (i.ITEM_POPULARITY_SCORE - s.MIN_POPULARITY) / NULLIF((s.MAX_POPULARITY - s.MIN_POPULARITY), 0)
    END AS NORMALIZED_POPULARITY_SCORE,

    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
FROM item_base i
CROSS JOIN stats s;


-- ============================================================
-- 3. Product catalog features
-- ============================================================

INSERT INTO CURATED.PRODUCT_CATALOG_FEATURES (
    ITEM_ID,
    CATEGORY_ID,
    PARENT_CATEGORY_ID,
    PROPERTY_COUNT,
    HAS_CATEGORY,
    PRODUCT_METADATA,
    CREATED_TS,
    UPDATED_TS
)
WITH latest_category AS (
    SELECT
        ITEM_ID,
        TRY_TO_NUMBER(PROPERTY_VALUE) AS CATEGORY_ID,
        ROW_NUMBER() OVER (
            PARTITION BY ITEM_ID
            ORDER BY PROPERTY_TS DESC
        ) AS RN
    FROM CURATED.CLEAN_RECOMART_ITEM_PROPERTIES
    WHERE PROPERTY_NAME = 'categoryid'
      AND SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID
),
property_summary AS (
    SELECT
        ITEM_ID,
        COUNT(*) AS PROPERTY_COUNT
    FROM CURATED.CLEAN_RECOMART_ITEM_PROPERTIES
    WHERE SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID
    GROUP BY ITEM_ID
)
SELECT
    p.ITEM_ID,
    c.CATEGORY_ID,
    ct.PARENT_CATEGORY_ID,
    p.PROPERTY_COUNT,
    CASE WHEN c.CATEGORY_ID IS NOT NULL THEN TRUE ELSE FALSE END AS HAS_CATEGORY,

    OBJECT_CONSTRUCT(
        'property_count', p.PROPERTY_COUNT,
        'category_id', c.CATEGORY_ID,
        'parent_category_id', ct.PARENT_CATEGORY_ID
    ) AS PRODUCT_METADATA,

    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
FROM property_summary p
LEFT JOIN latest_category c
    ON p.ITEM_ID = c.ITEM_ID
   AND c.RN = 1
LEFT JOIN CURATED.CLEAN_RECOMART_CATEGORY_TREE ct
    ON c.CATEGORY_ID = ct.CATEGORY_ID;