USE ROLE ACCOUNTADMIN;
USE DATABASE RECOMART_DB;

CREATE TABLE IF NOT EXISTS CURATED.FE_USER_ACTIVITY (
    USER_ID                         NUMBER(38,0),
    TOTAL_VIEWS                     NUMBER(38,0),
    TOTAL_ADD_TO_CARTS              NUMBER(38,0),
    TOTAL_TRANSACTIONS              NUMBER(38,0),
    UNIQUE_ITEMS_INTERACTED         NUMBER(38,0),
    UNIQUE_ITEMS_PURCHASED          NUMBER(38,0),
    AVG_IMPLICIT_SCORE              FLOAT,
    MAX_IMPLICIT_SCORE              FLOAT,
    USER_ACTIVITY_LEVEL             VARCHAR,
    NORMALIZED_TOTAL_VIEWS          FLOAT,
    NORMALIZED_TOTAL_TRANSACTIONS   FLOAT,
    SOURCE_VALIDATION_BATCH_ID      VARCHAR,
    FEATURE_VERSION                 VARCHAR,
    FEATURE_RUN_TS                  TIMESTAMP_NTZ,
    CREATED_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CURATED.FE_ITEM_POPULARITY (
    ITEM_ID                         NUMBER(38,0),
    TOTAL_VIEWS                     NUMBER(38,0),
    TOTAL_ADD_TO_CARTS              NUMBER(38,0),
    TOTAL_TRANSACTIONS              NUMBER(38,0),
    UNIQUE_USERS                    NUMBER(38,0),
    ITEM_POPULARITY_SCORE           FLOAT,
    NORMALIZED_POPULARITY_SCORE     FLOAT,
    CONVERSION_RATE                 FLOAT,
    ITEM_ACTIVITY_LEVEL             VARCHAR,
    SOURCE_VALIDATION_BATCH_ID      VARCHAR,
    FEATURE_VERSION                 VARCHAR,
    FEATURE_RUN_TS                  TIMESTAMP_NTZ,
    CREATED_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CURATED.FE_USER_CATEGORY_AFFINITY (
    USER_ID                         NUMBER(38,0),
    CATEGORY_ID                     NUMBER(38,0),
    PARENT_CATEGORY_ID              NUMBER(38,0),
    CATEGORY_VIEW_COUNT             NUMBER(38,0),
    CATEGORY_ADD_TO_CART_COUNT      NUMBER(38,0),
    CATEGORY_TRANSACTION_COUNT      NUMBER(38,0),
    CATEGORY_AFFINITY_SCORE         FLOAT,
    NORMALIZED_CATEGORY_AFFINITY    FLOAT,
    SOURCE_VALIDATION_BATCH_ID      VARCHAR,
    FEATURE_VERSION                 VARCHAR,
    FEATURE_RUN_TS                  TIMESTAMP_NTZ,
    CREATED_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CURATED.FE_ITEM_CO_OCCURRENCE (
    ITEM_ID                         NUMBER(38,0),
    CO_OCCUR_ITEM_ID                NUMBER(38,0),
    CO_INTERACTION_USERS            NUMBER(38,0),
    CO_INTERACTION_SCORE            FLOAT,
    SOURCE_VALIDATION_BATCH_ID      VARCHAR,
    FEATURE_VERSION                 VARCHAR,
    FEATURE_RUN_TS                  TIMESTAMP_NTZ,
    CREATED_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CURATED.FE_ITEM_SIMILARITY (
    ITEM_ID                         NUMBER(38,0),
    SIMILAR_ITEM_ID                 NUMBER(38,0),
    CO_INTERACTION_USERS            NUMBER(38,0),
    ITEM_USER_COUNT                 NUMBER(38,0),
    SIMILAR_ITEM_USER_COUNT         NUMBER(38,0),
    COSINE_SIMILARITY_SCORE         FLOAT,
    SOURCE_VALIDATION_BATCH_ID      VARCHAR,
    FEATURE_VERSION                 VARCHAR,
    FEATURE_RUN_TS                  TIMESTAMP_NTZ,
    CREATED_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CURATED.RECOMMENDATION_TRAINING_DATASET (
    USER_ID                         NUMBER(38,0),
    ITEM_ID                         NUMBER(38,0),

    USER_TOTAL_VIEWS                NUMBER(38,0),
    USER_TOTAL_ADD_TO_CARTS         NUMBER(38,0),
    USER_TOTAL_TRANSACTIONS         NUMBER(38,0),
    USER_ACTIVITY_LEVEL             VARCHAR,
    USER_AVG_IMPLICIT_SCORE         FLOAT,

    ITEM_TOTAL_VIEWS                NUMBER(38,0),
    ITEM_TOTAL_ADD_TO_CARTS         NUMBER(38,0),
    ITEM_TOTAL_TRANSACTIONS         NUMBER(38,0),
    ITEM_POPULARITY_SCORE           FLOAT,
    ITEM_CONVERSION_RATE            FLOAT,
    ITEM_ACTIVITY_LEVEL             VARCHAR,

    VIEW_COUNT                      NUMBER(38,0),
    ADD_TO_CART_COUNT               NUMBER(38,0),
    TRANSACTION_COUNT               NUMBER(38,0),
    USER_ITEM_IMPLICIT_SCORE        FLOAT,

    TARGET_LABEL                    FLOAT,

    SOURCE_VALIDATION_BATCH_ID      VARCHAR,
    FEATURE_VERSION                 VARCHAR,
    FEATURE_RUN_TS                  TIMESTAMP_NTZ,
    CREATED_TS                      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);