USE ROLE ACCOUNTADMIN;
USE DATABASE RECOMART_DB;

SET SOURCE_VALIDATION_BATCH_ID = (
    SELECT SOURCE_VALIDATION_BATCH_ID
    FROM CURATED.USER_ITEM_INTERACTIONS
    WHERE SOURCE_VALIDATION_BATCH_ID IS NOT NULL
    ORDER BY PREPARATION_RUN_TS DESC
    LIMIT 1
);

SET FEATURE_RUN_TS = CURRENT_TIMESTAMP();
SET FEATURE_VERSION = 'v1';

DELETE FROM CURATED.FE_USER_ACTIVITY
WHERE SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID;

INSERT INTO CURATED.FE_USER_ACTIVITY (
    USER_ID,
    TOTAL_VIEWS,
    TOTAL_ADD_TO_CARTS,
    TOTAL_TRANSACTIONS,
    UNIQUE_ITEMS_INTERACTED,
    UNIQUE_ITEMS_PURCHASED,
    AVG_IMPLICIT_SCORE,
    MAX_IMPLICIT_SCORE,
    USER_ACTIVITY_LEVEL,
    NORMALIZED_TOTAL_VIEWS,
    NORMALIZED_TOTAL_TRANSACTIONS,
    SOURCE_VALIDATION_BATCH_ID,
    FEATURE_VERSION,
    FEATURE_RUN_TS
)
WITH user_base AS (
    SELECT
        USER_ID,
        SUM(VIEW_COUNT) AS TOTAL_VIEWS,
        SUM(ADD_TO_CART_COUNT) AS TOTAL_ADD_TO_CARTS,
        SUM(TRANSACTION_COUNT) AS TOTAL_TRANSACTIONS,
        COUNT(DISTINCT ITEM_ID) AS UNIQUE_ITEMS_INTERACTED,
        COUNT(DISTINCT CASE WHEN TRANSACTION_COUNT > 0 THEN ITEM_ID END) AS UNIQUE_ITEMS_PURCHASED,
        AVG(IMPLICIT_SCORE) AS AVG_IMPLICIT_SCORE,
        MAX(IMPLICIT_SCORE) AS MAX_IMPLICIT_SCORE
    FROM CURATED.USER_ITEM_INTERACTIONS
    WHERE SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID
    GROUP BY USER_ID
),
stats AS (
    SELECT
        MIN(TOTAL_VIEWS) AS MIN_TOTAL_VIEWS,
        MAX(TOTAL_VIEWS) AS MAX_TOTAL_VIEWS,
        MIN(TOTAL_TRANSACTIONS) AS MIN_TOTAL_TRANSACTIONS,
        MAX(TOTAL_TRANSACTIONS) AS MAX_TOTAL_TRANSACTIONS
    FROM user_base
)
SELECT
    u.USER_ID,
    u.TOTAL_VIEWS,
    u.TOTAL_ADD_TO_CARTS,
    u.TOTAL_TRANSACTIONS,
    u.UNIQUE_ITEMS_INTERACTED,
    u.UNIQUE_ITEMS_PURCHASED,
    u.AVG_IMPLICIT_SCORE,
    u.MAX_IMPLICIT_SCORE,

    CASE
        WHEN u.TOTAL_TRANSACTIONS >= 5 OR u.TOTAL_VIEWS >= 50 THEN 'HIGH'
        WHEN u.TOTAL_TRANSACTIONS >= 1 OR u.TOTAL_VIEWS >= 10 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS USER_ACTIVITY_LEVEL,

    CASE
        WHEN s.MAX_TOTAL_VIEWS = s.MIN_TOTAL_VIEWS THEN 0
        ELSE (u.TOTAL_VIEWS - s.MIN_TOTAL_VIEWS) / NULLIF((s.MAX_TOTAL_VIEWS - s.MIN_TOTAL_VIEWS), 0)
    END AS NORMALIZED_TOTAL_VIEWS,

    CASE
        WHEN s.MAX_TOTAL_TRANSACTIONS = s.MIN_TOTAL_TRANSACTIONS THEN 0
        ELSE (u.TOTAL_TRANSACTIONS - s.MIN_TOTAL_TRANSACTIONS)
             / NULLIF((s.MAX_TOTAL_TRANSACTIONS - s.MIN_TOTAL_TRANSACTIONS), 0)
    END AS NORMALIZED_TOTAL_TRANSACTIONS,

    $SOURCE_VALIDATION_BATCH_ID,
    $FEATURE_VERSION,
    $FEATURE_RUN_TS
FROM user_base u
CROSS JOIN stats s;