USE ROLE ACCOUNTADMIN;
USE DATABASE RECOMART_DB;

SET SOURCE_VALIDATION_BATCH_ID = (
    SELECT SOURCE_VALIDATION_BATCH_ID
    FROM CURATED.USER_ITEM_INTERACTIONS
    WHERE SOURCE_VALIDATION_BATCH_ID IS NOT NULL
    ORDER BY PREPARATION_RUN_TS DESC
    LIMIT 1
);

SET FEATURE_RUN_TS = CURRENT_TIMESTAMP();
SET FEATURE_VERSION = 'v1';

DELETE FROM CURATED.FE_ITEM_POPULARITY
WHERE SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID;

INSERT INTO CURATED.FE_ITEM_POPULARITY (
    ITEM_ID,
    TOTAL_VIEWS,
    TOTAL_ADD_TO_CARTS,
    TOTAL_TRANSACTIONS,
    UNIQUE_USERS,
    ITEM_POPULARITY_SCORE,
    NORMALIZED_POPULARITY_SCORE,
    CONVERSION_RATE,
    ITEM_ACTIVITY_LEVEL,
    SOURCE_VALIDATION_BATCH_ID,
    FEATURE_VERSION,
    FEATURE_RUN_TS
)
WITH item_base AS (
    SELECT
        ITEM_ID,
        SUM(VIEW_COUNT) AS TOTAL_VIEWS,
        SUM(ADD_TO_CART_COUNT) AS TOTAL_ADD_TO_CARTS,
        SUM(TRANSACTION_COUNT) AS TOTAL_TRANSACTIONS,
        COUNT(DISTINCT USER_ID) AS UNIQUE_USERS,

        SUM(
            VIEW_COUNT * 1
            + ADD_TO_CART_COUNT * 3
            + TRANSACTION_COUNT * 5
        ) AS ITEM_POPULARITY_SCORE,

        CASE
            WHEN SUM(VIEW_COUNT) = 0 THEN 0
            ELSE SUM(TRANSACTION_COUNT) / NULLIF(SUM(VIEW_COUNT), 0)
        END AS CONVERSION_RATE
    FROM CURATED.USER_ITEM_INTERACTIONS
    WHERE SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID
    GROUP BY ITEM_ID
),
stats AS (
    SELECT
        MIN(ITEM_POPULARITY_SCORE) AS MIN_POPULARITY,
        MAX(ITEM_POPULARITY_SCORE) AS MAX_POPULARITY
    FROM item_base
)
SELECT
    i.ITEM_ID,
    i.TOTAL_VIEWS,
    i.TOTAL_ADD_TO_CARTS,
    i.TOTAL_TRANSACTIONS,
    i.UNIQUE_USERS,
    i.ITEM_POPULARITY_SCORE,

    CASE
        WHEN s.MAX_POPULARITY = s.MIN_POPULARITY THEN 0
        ELSE (i.ITEM_POPULARITY_SCORE - s.MIN_POPULARITY)
             / NULLIF((s.MAX_POPULARITY - s.MIN_POPULARITY), 0)
    END AS NORMALIZED_POPULARITY_SCORE,

    i.CONVERSION_RATE,

    CASE
        WHEN i.ITEM_POPULARITY_SCORE >= 100 THEN 'HIGH'
        WHEN i.ITEM_POPULARITY_SCORE >= 20 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS ITEM_ACTIVITY_LEVEL,

    $SOURCE_VALIDATION_BATCH_ID,
    $FEATURE_VERSION,
    $FEATURE_RUN_TS
FROM item_base i
CROSS JOIN stats s;