USE ROLE ACCOUNTADMIN;
USE DATABASE RECOMART_DB;

SET SOURCE_VALIDATION_BATCH_ID = (
    SELECT SOURCE_VALIDATION_BATCH_ID
    FROM CURATED.CLEAN_RECOMART_EVENTS
    WHERE SOURCE_VALIDATION_BATCH_ID IS NOT NULL
    ORDER BY PREPARATION_RUN_TS DESC
    LIMIT 1
);

SET FEATURE_RUN_TS = CURRENT_TIMESTAMP();
SET FEATURE_VERSION = 'v1';

DELETE FROM CURATED.FE_USER_CATEGORY_AFFINITY
WHERE SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID;

INSERT INTO CURATED.FE_USER_CATEGORY_AFFINITY (
    USER_ID,
    CATEGORY_ID,
    PARENT_CATEGORY_ID,
    CATEGORY_VIEW_COUNT,
    CATEGORY_ADD_TO_CART_COUNT,
    CATEGORY_TRANSACTION_COUNT,
    CATEGORY_AFFINITY_SCORE,
    NORMALIZED_CATEGORY_AFFINITY,
    SOURCE_VALIDATION_BATCH_ID,
    FEATURE_VERSION,
    FEATURE_RUN_TS
)
WITH item_category AS (
    SELECT
        ITEM_ID,
        TRY_TO_NUMBER(PROPERTY_VALUE) AS CATEGORY_ID
    FROM CURATED.CLEAN_RECOMART_ITEM_PROPERTIES
    WHERE PROPERTY_NAME = 'categoryid'
      AND SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY ITEM_ID
        ORDER BY PROPERTY_TS DESC
    ) = 1
),
category_base AS (
    SELECT
        e.USER_ID,
        ic.CATEGORY_ID,
        ct.PARENT_CATEGORY_ID,

        COUNT_IF(e.EVENT_TYPE = 'view') AS CATEGORY_VIEW_COUNT,
        COUNT_IF(e.EVENT_TYPE = 'addtocart') AS CATEGORY_ADD_TO_CART_COUNT,
        COUNT_IF(e.EVENT_TYPE = 'transaction') AS CATEGORY_TRANSACTION_COUNT,

        SUM(e.EVENT_WEIGHT) AS CATEGORY_AFFINITY_SCORE
    FROM CURATED.CLEAN_RECOMART_EVENTS e
    INNER JOIN item_category ic
        ON e.ITEM_ID = ic.ITEM_ID
    LEFT JOIN CURATED.CLEAN_RECOMART_CATEGORY_TREE ct
        ON ic.CATEGORY_ID = ct.CATEGORY_ID
       AND ct.SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID
    WHERE e.SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID
    GROUP BY
        e.USER_ID,
        ic.CATEGORY_ID,
        ct.PARENT_CATEGORY_ID
),
stats AS (
    SELECT
        MIN(CATEGORY_AFFINITY_SCORE) AS MIN_AFFINITY,
        MAX(CATEGORY_AFFINITY_SCORE) AS MAX_AFFINITY
    FROM category_base
)
SELECT
    c.USER_ID,
    c.CATEGORY_ID,
    c.PARENT_CATEGORY_ID,
    c.CATEGORY_VIEW_COUNT,
    c.CATEGORY_ADD_TO_CART_COUNT,
    c.CATEGORY_TRANSACTION_COUNT,
    c.CATEGORY_AFFINITY_SCORE,

    CASE
        WHEN s.MAX_AFFINITY = s.MIN_AFFINITY THEN 0
        ELSE (c.CATEGORY_AFFINITY_SCORE - s.MIN_AFFINITY)
             / NULLIF((s.MAX_AFFINITY - s.MIN_AFFINITY), 0)
    END AS NORMALIZED_CATEGORY_AFFINITY,

    $SOURCE_VALIDATION_BATCH_ID,
    $FEATURE_VERSION,
    $FEATURE_RUN_TS
FROM category_base c
CROSS JOIN stats s;