USE ROLE ACCOUNTADMIN;
USE DATABASE RECOMART_DB;

SET SOURCE_VALIDATION_BATCH_ID = (
    SELECT SOURCE_VALIDATION_BATCH_ID
    FROM CURATED.USER_ITEM_INTERACTIONS
    WHERE SOURCE_VALIDATION_BATCH_ID IS NOT NULL
    ORDER BY PREPARATION_RUN_TS DESC
    LIMIT 1
);

SET FEATURE_RUN_TS = CURRENT_TIMESTAMP();
SET FEATURE_VERSION = 'v1';

DELETE FROM CURATED.FE_ITEM_CO_OCCURRENCE
WHERE SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID;

DELETE FROM CURATED.FE_ITEM_SIMILARITY
WHERE SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID;

-- ============================================================
-- Create item co-occurrence
-- To control pair explosion, ignore users with more than 100 interacted items.
-- ============================================================

INSERT INTO CURATED.FE_ITEM_CO_OCCURRENCE (
    ITEM_ID,
    CO_OCCUR_ITEM_ID,
    CO_INTERACTION_USERS,
    CO_INTERACTION_SCORE,
    SOURCE_VALIDATION_BATCH_ID,
    FEATURE_VERSION,
    FEATURE_RUN_TS
)
WITH qualified_users AS (
    SELECT
        USER_ID
    FROM CURATED.USER_ITEM_INTERACTIONS
    WHERE SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID
    GROUP BY USER_ID
    HAVING COUNT(DISTINCT ITEM_ID) BETWEEN 2 AND 100
),
user_items AS (
    SELECT
        ui.USER_ID,
        ui.ITEM_ID,
        ui.IMPLICIT_SCORE
    FROM CURATED.USER_ITEM_INTERACTIONS ui
    INNER JOIN qualified_users qu
        ON ui.USER_ID = qu.USER_ID
    WHERE ui.SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID
),
item_pairs AS (
    SELECT
        a.ITEM_ID AS ITEM_ID,
        b.ITEM_ID AS CO_OCCUR_ITEM_ID,
        COUNT(DISTINCT a.USER_ID) AS CO_INTERACTION_USERS,
        SUM(LEAST(a.IMPLICIT_SCORE, b.IMPLICIT_SCORE)) AS CO_INTERACTION_SCORE
    FROM user_items a
    INNER JOIN user_items b
        ON a.USER_ID = b.USER_ID
       AND a.ITEM_ID < b.ITEM_ID
    GROUP BY
        a.ITEM_ID,
        b.ITEM_ID
),
both_directions AS (
    SELECT
        ITEM_ID,
        CO_OCCUR_ITEM_ID,
        CO_INTERACTION_USERS,
        CO_INTERACTION_SCORE
    FROM item_pairs

    UNION ALL

    SELECT
        CO_OCCUR_ITEM_ID AS ITEM_ID,
        ITEM_ID AS CO_OCCUR_ITEM_ID,
        CO_INTERACTION_USERS,
        CO_INTERACTION_SCORE
    FROM item_pairs
)
SELECT
    ITEM_ID,
    CO_OCCUR_ITEM_ID,
    CO_INTERACTION_USERS,
    CO_INTERACTION_SCORE,
    $SOURCE_VALIDATION_BATCH_ID,
    $FEATURE_VERSION,
    $FEATURE_RUN_TS
FROM both_directions;


-- ============================================================
-- Create cosine-style item similarity
-- ============================================================

INSERT INTO CURATED.FE_ITEM_SIMILARITY (
    ITEM_ID,
    SIMILAR_ITEM_ID,
    CO_INTERACTION_USERS,
    ITEM_USER_COUNT,
    SIMILAR_ITEM_USER_COUNT,
    COSINE_SIMILARITY_SCORE,
    SOURCE_VALIDATION_BATCH_ID,
    FEATURE_VERSION,
    FEATURE_RUN_TS
)
WITH item_user_counts AS (
    SELECT
        ITEM_ID,
        COUNT(DISTINCT USER_ID) AS ITEM_USER_COUNT
    FROM CURATED.USER_ITEM_INTERACTIONS
    WHERE SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID
    GROUP BY ITEM_ID
)
SELECT
    c.ITEM_ID,
    c.CO_OCCUR_ITEM_ID AS SIMILAR_ITEM_ID,
    c.CO_INTERACTION_USERS,
    i1.ITEM_USER_COUNT,
    i2.ITEM_USER_COUNT AS SIMILAR_ITEM_USER_COUNT,

    c.CO_INTERACTION_USERS
    / NULLIF(SQRT(i1.ITEM_USER_COUNT * i2.ITEM_USER_COUNT), 0) AS COSINE_SIMILARITY_SCORE,

    $SOURCE_VALIDATION_BATCH_ID,
    $FEATURE_VERSION,
    $FEATURE_RUN_TS
FROM CURATED.FE_ITEM_CO_OCCURRENCE c
INNER JOIN item_user_counts i1
    ON c.ITEM_ID = i1.ITEM_ID
INNER JOIN item_user_counts i2
    ON c.CO_OCCUR_ITEM_ID = i2.ITEM_ID
WHERE c.SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID;