SELECT COUNT(*) AS USER_ACTIVITY_FEATURES
FROM CURATED.FE_USER_ACTIVITY;

SELECT COUNT(*) AS ITEM_POPULARITY_FEATURES
FROM CURATED.FE_ITEM_POPULARITY;

SELECT COUNT(*) AS USER_CATEGORY_AFFINITY_FEATURES
FROM CURATED.FE_USER_CATEGORY_AFFINITY;

SELECT COUNT(*) AS ITEM_CO_OCCURRENCE_FEATURES
FROM CURATED.FE_ITEM_CO_OCCURRENCE;

SELECT COUNT(*) AS ITEM_SIMILARITY_FEATURES
FROM CURATED.FE_ITEM_SIMILARITY;

SELECT COUNT(*) AS TRAINING_DATASET_ROWS
FROM CURATED.RECOMMENDATION_TRAINING_DATASET;

SELECT
    ITEM_ID,
    SIMILAR_ITEM_ID,
    CO_INTERACTION_USERS,
    COSINE_SIMILARITY_SCORE
FROM CURATED.FE_ITEM_SIMILARITY
ORDER BY COSINE_SIMILARITY_SCORE DESC
LIMIT 20;

SELECT *
FROM CURATED.RECOMMENDATION_TRAINING_DATASET
LIMIT 20;