USE ROLE ACCOUNTADMIN;
USE DATABASE RECOMART_DB;

SET SOURCE_VALIDATION_BATCH_ID = (
    SELECT SOURCE_VALIDATION_BATCH_ID
    FROM CURATED.RECOMMENDATION_TRAINING_DATASET
    WHERE SOURCE_VALIDATION_BATCH_ID IS NOT NULL
    ORDER BY FEATURE_RUN_TS DESC
    LIMIT 1
);

SET FEATURE_VERSION = 'v1';

DELETE FROM FEATURE_STORE.FEATURE_REGISTRY
WHERE FEATURE_VERSION = $FEATURE_VERSION
  AND SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID;

INSERT INTO FEATURE_STORE.FEATURE_REGISTRY (
    FEATURE_ID,
    FEATURE_NAME,
    FEATURE_GROUP,
    ENTITY_TYPE,
    ENTITY_KEY,
    SOURCE_TABLE,
    SOURCE_COLUMN,
    TRANSFORMATION_LOGIC,
    DATA_TYPE,
    FEATURE_VERSION,
    SOURCE_VALIDATION_BATCH_ID,
    IS_ACTIVE,
    CREATED_BY,
    CREATED_TS,
    UPDATED_TS
)
VALUES
(
    'FS_USER_001',
    'user_total_views',
    'user_activity',
    'user',
    'USER_ID',
    'CURATED.FE_USER_ACTIVITY',
    'TOTAL_VIEWS',
    'Total number of product view events by user',
    'NUMBER',
    $FEATURE_VERSION,
    $SOURCE_VALIDATION_BATCH_ID,
    TRUE,
    CURRENT_USER(),
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
),
(
    'FS_USER_002',
    'user_total_add_to_carts',
    'user_activity',
    'user',
    'USER_ID',
    'CURATED.FE_USER_ACTIVITY',
    'TOTAL_ADD_TO_CARTS',
    'Total number of add-to-cart events by user',
    'NUMBER',
    $FEATURE_VERSION,
    $SOURCE_VALIDATION_BATCH_ID,
    TRUE,
    CURRENT_USER(),
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
),
(
    'FS_USER_003',
    'user_total_transactions',
    'user_activity',
    'user',
    'USER_ID',
    'CURATED.FE_USER_ACTIVITY',
    'TOTAL_TRANSACTIONS',
    'Total number of transaction events by user',
    'NUMBER',
    $FEATURE_VERSION,
    $SOURCE_VALIDATION_BATCH_ID,
    TRUE,
    CURRENT_USER(),
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
),
(
    'FS_USER_004',
    'user_activity_level',
    'user_activity',
    'user',
    'USER_ID',
    'CURATED.FE_USER_ACTIVITY',
    'USER_ACTIVITY_LEVEL',
    'User segmentation based on views and transactions',
    'VARCHAR',
    $FEATURE_VERSION,
    $SOURCE_VALIDATION_BATCH_ID,
    TRUE,
    CURRENT_USER(),
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
),
(
    'FS_USER_005',
    'user_avg_implicit_score',
    'user_activity',
    'user',
    'USER_ID',
    'CURATED.FE_USER_ACTIVITY',
    'AVG_IMPLICIT_SCORE',
    'Average implicit score across user-item interactions',
    'FLOAT',
    $FEATURE_VERSION,
    $SOURCE_VALIDATION_BATCH_ID,
    TRUE,
    CURRENT_USER(),
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
),
(
    'FS_ITEM_001',
    'item_total_views',
    'item_popularity',
    'item',
    'ITEM_ID',
    'CURATED.FE_ITEM_POPULARITY',
    'TOTAL_VIEWS',
    'Total number of views received by item',
    'NUMBER',
    $FEATURE_VERSION,
    $SOURCE_VALIDATION_BATCH_ID,
    TRUE,
    CURRENT_USER(),
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
),
(
    'FS_ITEM_002',
    'item_total_add_to_carts',
    'item_popularity',
    'item',
    'ITEM_ID',
    'CURATED.FE_ITEM_POPULARITY',
    'TOTAL_ADD_TO_CARTS',
    'Total number of add-to-cart events received by item',
    'NUMBER',
    $FEATURE_VERSION,
    $SOURCE_VALIDATION_BATCH_ID,
    TRUE,
    CURRENT_USER(),
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
),
(
    'FS_ITEM_003',
    'item_total_transactions',
    'item_popularity',
    'item',
    'ITEM_ID',
    'CURATED.FE_ITEM_POPULARITY',
    'TOTAL_TRANSACTIONS',
    'Total number of transactions for item',
    'NUMBER',
    $FEATURE_VERSION,
    $SOURCE_VALIDATION_BATCH_ID,
    TRUE,
    CURRENT_USER(),
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
),
(
    'FS_ITEM_004',
    'item_popularity_score',
    'item_popularity',
    'item',
    'ITEM_ID',
    'CURATED.FE_ITEM_POPULARITY',
    'ITEM_POPULARITY_SCORE',
    'Weighted score using view=1, addtocart=3, transaction=5',
    'FLOAT',
    $FEATURE_VERSION,
    $SOURCE_VALIDATION_BATCH_ID,
    TRUE,
    CURRENT_USER(),
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
),
(
    'FS_ITEM_005',
    'item_conversion_rate',
    'item_popularity',
    'item',
    'ITEM_ID',
    'CURATED.FE_ITEM_POPULARITY',
    'CONVERSION_RATE',
    'Transactions divided by views for item',
    'FLOAT',
    $FEATURE_VERSION,
    $SOURCE_VALIDATION_BATCH_ID,
    TRUE,
    CURRENT_USER(),
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
),
(
    'FS_INTERACTION_001',
    'user_item_implicit_score',
    'interaction',
    'user_item',
    'USER_ID,ITEM_ID',
    'CURATED.RECOMMENDATION_TRAINING_DATASET',
    'USER_ITEM_IMPLICIT_SCORE',
    'Weighted interaction score based on user event behavior',
    'FLOAT',
    $FEATURE_VERSION,
    $SOURCE_VALIDATION_BATCH_ID,
    TRUE,
    CURRENT_USER(),
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
),
(
    'FS_LABEL_001',
    'target_label',
    'training_label',
    'user_item',
    'USER_ID,ITEM_ID',
    'CURATED.RECOMMENDATION_TRAINING_DATASET',
    'TARGET_LABEL',
    'Derived label: transaction=1.0, addtocart=0.7, view=0.3',
    'FLOAT',
    $FEATURE_VERSION,
    $SOURCE_VALIDATION_BATCH_ID,
    TRUE,
    CURRENT_USER(),
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
);