USE ROLE ACCOUNTADMIN;
USE DATABASE RECOMART_DB;

SET SOURCE_VALIDATION_BATCH_ID = (
    SELECT SOURCE_VALIDATION_BATCH_ID
    FROM CURATED.RECOMMENDATION_TRAINING_DATASET
    WHERE SOURCE_VALIDATION_BATCH_ID IS NOT NULL
    ORDER BY FEATURE_RUN_TS DESC
    LIMIT 1
);

SET FEATURE_VERSION = 'v1';

DELETE FROM FEATURE_STORE.OFFLINE_RECOMMENDATION_FEATURES
WHERE SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID
  AND FEATURE_VERSION = $FEATURE_VERSION;

INSERT INTO FEATURE_STORE.OFFLINE_RECOMMENDATION_FEATURES (
    USER_ID,
    ITEM_ID,

    USER_TOTAL_VIEWS,
    USER_TOTAL_ADD_TO_CARTS,
    USER_TOTAL_TRANSACTIONS,
    USER_ACTIVITY_LEVEL,
    USER_AVG_IMPLICIT_SCORE,

    ITEM_TOTAL_VIEWS,
    ITEM_TOTAL_ADD_TO_CARTS,
    ITEM_TOTAL_TRANSACTIONS,
    ITEM_POPULARITY_SCORE,
    ITEM_CONVERSION_RATE,
    ITEM_ACTIVITY_LEVEL,

    VIEW_COUNT,
    ADD_TO_CART_COUNT,
    TRANSACTION_COUNT,
    USER_ITEM_IMPLICIT_SCORE,

    TARGET_LABEL,

    FEATURE_VERSION,
    SOURCE_VALIDATION_BATCH_ID,
    FEATURE_RUN_TS,
    FEATURE_PUBLISHED_TS
)
SELECT
    USER_ID,
    ITEM_ID,

    USER_TOTAL_VIEWS,
    USER_TOTAL_ADD_TO_CARTS,
    USER_TOTAL_TRANSACTIONS,
    USER_ACTIVITY_LEVEL,
    USER_AVG_IMPLICIT_SCORE,

    ITEM_TOTAL_VIEWS,
    ITEM_TOTAL_ADD_TO_CARTS,
    ITEM_TOTAL_TRANSACTIONS,
    ITEM_POPULARITY_SCORE,
    ITEM_CONVERSION_RATE,
    ITEM_ACTIVITY_LEVEL,

    VIEW_COUNT,
    ADD_TO_CART_COUNT,
    TRANSACTION_COUNT,
    USER_ITEM_IMPLICIT_SCORE,

    TARGET_LABEL,

    FEATURE_VERSION,
    SOURCE_VALIDATION_BATCH_ID,
    FEATURE_RUN_TS,
    CURRENT_TIMESTAMP()
FROM CURATED.RECOMMENDATION_TRAINING_DATASET
WHERE SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID
  AND FEATURE_VERSION = $FEATURE_VERSION;