USE ROLE ACCOUNTADMIN;
USE DATABASE RECOMART_DB;

SET SOURCE_VALIDATION_BATCH_ID = (
    SELECT SOURCE_VALIDATION_BATCH_ID
    FROM CURATED.RECOMMENDATION_TRAINING_DATASET
    WHERE SOURCE_VALIDATION_BATCH_ID IS NOT NULL
    ORDER BY FEATURE_RUN_TS DESC
    LIMIT 1
);

SET FEATURE_VERSION = 'v1';

DELETE FROM FEATURE_STORE.ONLINE_RECOMMENDATION_FEATURES
WHERE SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID
  AND FEATURE_VERSION = $FEATURE_VERSION;

INSERT INTO FEATURE_STORE.ONLINE_RECOMMENDATION_FEATURES (
    USER_ID,
    ITEM_ID,

    USER_ACTIVITY_LEVEL,
    USER_AVG_IMPLICIT_SCORE,

    ITEM_POPULARITY_SCORE,
    ITEM_CONVERSION_RATE,
    ITEM_ACTIVITY_LEVEL,

    USER_ITEM_IMPLICIT_SCORE,
    RECOMMENDATION_CANDIDATE_SCORE,

    FEATURE_VERSION,
    SOURCE_VALIDATION_BATCH_ID,
    LAST_UPDATED_TS
)
SELECT
    USER_ID,
    ITEM_ID,

    USER_ACTIVITY_LEVEL,
    USER_AVG_IMPLICIT_SCORE,

    ITEM_POPULARITY_SCORE,
    ITEM_CONVERSION_RATE,
    ITEM_ACTIVITY_LEVEL,

    USER_ITEM_IMPLICIT_SCORE,

    (
        COALESCE(USER_ITEM_IMPLICIT_SCORE, 0) * 0.50
        + COALESCE(ITEM_POPULARITY_SCORE, 0) * 0.30
        + COALESCE(ITEM_CONVERSION_RATE, 0) * 0.20
    ) AS RECOMMENDATION_CANDIDATE_SCORE,

    FEATURE_VERSION,
    SOURCE_VALIDATION_BATCH_ID,
    CURRENT_TIMESTAMP()
FROM FEATURE_STORE.OFFLINE_RECOMMENDATION_FEATURES
WHERE SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID
  AND FEATURE_VERSION = $FEATURE_VERSION;