USE ROLE ACCOUNTADMIN;
USE DATABASE RECOMART_DB;

SET SOURCE_VALIDATION_BATCH_ID = (
    SELECT SOURCE_VALIDATION_BATCH_ID
    FROM FEATURE_STORE.OFFLINE_RECOMMENDATION_FEATURES
    WHERE SOURCE_VALIDATION_BATCH_ID IS NOT NULL
    ORDER BY FEATURE_PUBLISHED_TS DESC
    LIMIT 1
);

SET FEATURE_VERSION = 'v1';

-- ============================================================
-- 1. View active feature metadata
-- ============================================================

SELECT
    FEATURE_ID,
    FEATURE_NAME,
    FEATURE_GROUP,
    ENTITY_TYPE,
    ENTITY_KEY,
    SOURCE_TABLE,
    SOURCE_COLUMN,
    TRANSFORMATION_LOGIC,
    DATA_TYPE,
    FEATURE_VERSION,
    SOURCE_VALIDATION_BATCH_ID,
    IS_ACTIVE
FROM FEATURE_STORE.FEATURE_REGISTRY
WHERE FEATURE_VERSION = $FEATURE_VERSION
  AND SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID
  AND IS_ACTIVE = TRUE
ORDER BY FEATURE_GROUP, FEATURE_NAME;


-- ============================================================
-- 2. Retrieve offline features for model training
-- ============================================================

SELECT
    USER_ID,
    ITEM_ID,

    USER_TOTAL_VIEWS,
    USER_TOTAL_ADD_TO_CARTS,
    USER_TOTAL_TRANSACTIONS,
    USER_ACTIVITY_LEVEL,
    USER_AVG_IMPLICIT_SCORE,

    ITEM_TOTAL_VIEWS,
    ITEM_TOTAL_ADD_TO_CARTS,
    ITEM_TOTAL_TRANSACTIONS,
    ITEM_POPULARITY_SCORE,
    ITEM_CONVERSION_RATE,
    ITEM_ACTIVITY_LEVEL,

    USER_ITEM_IMPLICIT_SCORE,
    TARGET_LABEL,

    FEATURE_VERSION,
    SOURCE_VALIDATION_BATCH_ID
FROM FEATURE_STORE.OFFLINE_RECOMMENDATION_FEATURES
WHERE FEATURE_VERSION = $FEATURE_VERSION
  AND SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID
LIMIT 50;


-- ============================================================
-- 3. Retrieve online features for one sample user
-- ============================================================

SET SAMPLE_USER_ID = (
    SELECT USER_ID
    FROM FEATURE_STORE.ONLINE_RECOMMENDATION_FEATURES
    WHERE SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID
    ORDER BY RECOMMENDATION_CANDIDATE_SCORE DESC
    LIMIT 1
);

SELECT
    USER_ID,
    ITEM_ID,
    USER_ACTIVITY_LEVEL,
    ITEM_POPULARITY_SCORE,
    ITEM_CONVERSION_RATE,
    USER_ITEM_IMPLICIT_SCORE,
    RECOMMENDATION_CANDIDATE_SCORE,
    FEATURE_VERSION,
    SOURCE_VALIDATION_BATCH_ID
FROM FEATURE_STORE.ONLINE_RECOMMENDATION_FEATURES
WHERE USER_ID = $SAMPLE_USER_ID
  AND FEATURE_VERSION = $FEATURE_VERSION
  AND SOURCE_VALIDATION_BATCH_ID = $SOURCE_VALIDATION_BATCH_ID
ORDER BY RECOMMENDATION_CANDIDATE_SCORE DESC
LIMIT 10;


-- ============================================================
-- 4. Insert feature retrieval audit log
-- ============================================================

INSERT INTO FEATURE_STORE.FEATURE_RETRIEVAL_LOG (
    REQUEST_ID,
    USER_ID,
    ITEM_ID,
    FEATURE_VERSION,
    SOURCE_VALIDATION_BATCH_ID,
    REQUEST_TYPE,
    REQUEST_TS,
    STATUS,
    MESSAGE
)
SELECT
    UUID_STRING(),
    $SAMPLE_USER_ID,
    NULL,
    $FEATURE_VERSION,
    $SOURCE_VALIDATION_BATCH_ID,
    'ONLINE_INFERENCE_DEMO',
    CURRENT_TIMESTAMP(),
    'SUCCESS',
    'Retrieved top online recommendation features for sample user';