-- Check feature registry
SELECT
    FEATURE_GROUP,
    COUNT(*) AS FEATURE_COUNT
FROM FEATURE_STORE.FEATURE_REGISTRY
WHERE IS_ACTIVE = TRUE
GROUP BY FEATURE_GROUP
ORDER BY FEATURE_GROUP;

--Check offline features

SELECT COUNT(*) AS OFFLINE_FEATURE_ROWS
FROM FEATURE_STORE.OFFLINE_RECOMMENDATION_FEATURES;

--Check online features

SELECT COUNT(*) AS ONLINE_FEATURE_ROWS
FROM FEATURE_STORE.ONLINE_RECOMMENDATION_FEATURES;

--Check latest feature versions

SELECT
    FEATURE_VERSION,
    SOURCE_VALIDATION_BATCH_ID,
    COUNT(*) AS FEATURE_ROWS,
    MAX(FEATURE_PUBLISHED_TS) AS LATEST_PUBLISHED_TS
FROM FEATURE_STORE.OFFLINE_RECOMMENDATION_FEATURES
GROUP BY FEATURE_VERSION, SOURCE_VALIDATION_BATCH_ID
ORDER BY LATEST_PUBLISHED_TS DESC;

--Check retrieval log

SELECT *
FROM FEATURE_STORE.FEATURE_RETRIEVAL_LOG
ORDER BY REQUEST_TS DESC
LIMIT 20;