USE ROLE ACCOUNTADMIN;
USE DATABASE RECOMART_DB;

CREATE TABLE IF NOT EXISTS OPS.DATASET_VERSION_REGISTRY (
    DATASET_VERSION_ID      VARCHAR,
    DATASET_NAME            VARCHAR,
    SOURCE_TYPE             VARCHAR,
    LOCAL_PATH              VARCHAR,
    S3_RAW_PATH             VARCHAR,
    TARGET_TABLE            VARCHAR,
    DVC_REMOTE_PATH         VARCHAR,
    FILE_SIZE_BYTES         NUMBER(38,0),
    ROW_COUNT               NUMBER(38,0),
    SHA256_HASH             VARCHAR,
    VERSIONING_TOOL         VARCHAR,
    VERSION_STATUS          VARCHAR,
    MANIFEST_CREATED_TS     TIMESTAMP_NTZ,
    REGISTERED_TS           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    REGISTERED_BY           VARCHAR DEFAULT CURRENT_USER()
);

CREATE TABLE IF NOT EXISTS OPS.DATA_LINEAGE (
    LINEAGE_ID              VARCHAR,
    BATCH_ID                VARCHAR,
    SOURCE_OBJECT           VARCHAR,
    TARGET_OBJECT           VARCHAR,
    TRANSFORMATION_NAME     VARCHAR,
    TRANSFORMATION_TYPE     VARCHAR,
    TRANSFORMATION_LOGIC    VARCHAR,
    SOURCE_LAYER            VARCHAR,
    TARGET_LAYER            VARCHAR,
    START_TS                TIMESTAMP_NTZ,
    END_TS                  TIMESTAMP_NTZ,
    STATUS                  VARCHAR,
    CREATED_TS              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);