SELECT
    BATCH_ID,
    SOURCE_LAYER,
    TARGET_LAYER,
    TRANSFORMATION_NAME,
    TRANSFORMATION_TYPE,
    STATUS,
    CREATED_TS
FROM OPS.DATA_LINEAGE
ORDER BY CREATED_TS DESC;

SELECT
    DATASET_NAME,
    ROW_COUNT,
    SHA256_HASH,
    VERSIONING_TOOL,
    VERSION_STATUS,
    REGISTERED_TS
FROM OPS.DATASET_VERSION_REGISTRY
ORDER BY REGISTERED_TS DESC;

SELECT
    BATCH_ID,
    SOURCE_LAYER,
    TARGET_LAYER,
    TRANSFORMATION_NAME,
    TRANSFORMATION_TYPE,
    STATUS,
    CREATED_TS
FROM OPS.DATA_LINEAGE
ORDER BY CREATED_TS;