USE DATABASE RECOMART_DB;
USE WAREHOUSE RECOMART_WH;

SELECT COUNT(*) AS EVENT_COUNT
FROM RAW.RAW_RECOMART_EVENTS;

SELECT COUNT(*) AS ITEM_PROPERTY_COUNT
FROM RAW.RAW_RECOMART_ITEM_PROPERTIES;

SELECT COUNT(*) AS CATEGORY_COUNT
FROM RAW.RAW_RECOMART_CATEGORY_TREE;

SELECT COUNT(*) AS EXTERNAL_PRODUCT_RECORDS
FROM RAW.RAW_EXTERNAL_PRODUCTS;